# Generated by Django 3.1.1 on 2020-10-03 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='voted_users',
            field=models.ManyToManyField(blank=True, related_name='voted_users', to='user.UserExtension'),
        ),
    ]
