# Generated by Django 3.1.1 on 2020-09-25 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vote',
            name='who_voted',
        ),
        migrations.AddField(
            model_name='vote',
            name='who_voted',
            field=models.ManyToManyField(blank=True, to='user.UserExtension'),
        ),
    ]
