# Generated by Django 3.1.1 on 2020-09-25 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20200925_2248'),
    ]

    operations = [
        migrations.AddField(
            model_name='genre',
            name='num',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
