# Generated by Django 3.1.1 on 2020-10-15 17:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_userextension_check'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userextension',
            name='check',
        ),
    ]
