# Generated by Django 3.1.1 on 2020-09-25 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_genre_num'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='grade',
            field=models.CharField(max_length=50),
        ),
    ]
