# Generated by Django 3.1.1 on 2020-09-26 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_auto_20200925_2335'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='total_audience',
        ),
        migrations.AlterField(
            model_name='movie',
            name='released_date',
            field=models.IntegerField(null=True),
        ),
    ]
